### ISSUE TITLE
Which Version of MongoDB is being used?

### ISSUE THREAD

**Issue by dmcgill50** [robertwatkins/playground-robert-ultimate-tictactoe#2]
I am wanting to make sure that I use a consistent version on the MongoDB supported. Can you comment on which version we are supporting?

**Comment by robertwatkins** [comment]
the version on my mac is 3.0.1

**Comment by dmcgill50** [comment]
Thanks!

On Thu, Jul 30, 2015 at 11:25 AM, robertwatkins <notifications@github.com>
wrote:

> the version on my mac is 3.0.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertwatkins/playground-robert-ultimate-tictactoe/issues/2#issuecomment-126392592>
> .
>



-- 
David
